causas/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ver_causas),
    path('buscar/', views.buscar),
    path('ver/<nro_expediente>/', views.ver_causa),
    path('modificar/<nro_expediente>/', views.modificar_causa),
    path('eliminar/<nro_expediente>/', views.eliminar_causa),
    path('ingreso/', views.nueva_causa),
    path('remover/<int:ci>/de/<nro_expediente>', views.remover_persona),
    path('actividades/nueva/', views.agregar_actividad),
    path('actividades/registrar', views.registrar_actividad),
    path('triaje/<nro_expediente>/', views.agregar_triaje),
]

smc/urls.py
# from django.contrib import admin
from django.urls import path, include
from smc import views
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.index),
    path('home/', views.home),
    path('login/', views.login_),
    path('logout', views.logout_),
    path('causas/', include('causas.urls')),
    path('personas/', include('personas.urls')),
    path('talleres/', include('talleres.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('estadisticas/', views.estadisticas),
    path('gestion/', include('administracion.urls', namespace = 'gestion')),
    path('edit_bloqueado.html', views.edit_bloqueado),
]

causas/models.py
from django.db import models
from datetime import date, datetime, timedelta

from personas.models import Persona

# Create your models here.


class Causa(models.Model):
    PENDIENTE = 'Pendiente'
    ACTIVO = 'Activo'
    CULMINADO = 'Culminado'
    OPCIONES_ESTADO = (
        (PENDIENTE, 'Pendiente'),
        (ACTIVO, 'Activo'),
        (CULMINADO, 'Culminado')
    )

    EVA_PSICOLOGICA = 'Evaluación Psicológica'
    EVA_SOCIAL = 'Evaluación Social'
    EVA_PSICO_SOCIAL = 'Evaluación Psico-Social'
    TRIAJE = 'Triaje'
    TALLER = 'Taller'
    ORIENTACION = 'Orientación'
    PRUEBA_ANTICIPADA = 'Prueba Anticipada'
    OPCIONES_SOLICITUDES = (
        (EVA_PSICOLOGICA, 'Evaluación Psicológica'),
        (EVA_SOCIAL, 'Evaluación Social'),
        (EVA_PSICO_SOCIAL, 'Evaluación Psico-Social'),
        (TRIAJE, 'Triaje'),
        (TALLER, 'Taller'),
        (ORIENTACION, 'Orientación'),
        (PRUEBA_ANTICIPADA, 'Prueba Anticipada')
    )

    CONTROL_1 = 'Control 1'
    CONTROL_2 = 'Control 2'
    CONTROL_3 = 'Control 3'
    JUICIO_1 = 'Juicio 1'
    JUICIO_2 = 'Juicio 2'
    EJECUCION = 'Ejecución'
    OTROS = 'Otros Tribunales'

    OPCIONES_PROCEDENCIA = (
        (CONTROL_1, 'Control 1'),
        (CONTROL_2, 'Control 2'),
        (CONTROL_3, 'Control 3'),
        (JUICIO_1, 'Juicio 1'),
        (JUICIO_2, 'Juicio 2'),
        (EJECUCION, 'Ejecución'),
        (OTROS, 'Otros Tribunales')
    )

    PSICOLOGICA = 'Violencia Psicológica'
    ACOSO_HOST = 'Acoso u Hostigamiento'
    AMENAZA = 'Amenaza'
    FISICA = 'Violencia Física'
    FISICA_AGR = 'Violencia Física Agravada'
    SEXUAL = 'Violencia Sexual'
    ACT_CARN_VICT_VUL = 'Acto Carnal con Víctima Vulnerable'
    ACT_LASC = 'Actos Lascivos'
    PROST_FORZADA = 'Prostitución Forzada'
    ESCLAVITUD_SEXUAL = 'Esclavitud Sexual'
    ACOSO_SEXUAL = 'Acoso Sexual'
    LABORAL = 'Violencia Laboral'
    PATRIM_ECO = 'Violencia Patrimonial y Económica'
    OBSTETRICA = 'Violencia Obstétrica'
    ESTERIL_FORZADA = 'Esterilización Forzada'
    OFENSA_PUBLICA = 'Ofensa Pública'
    INSTITUCIONAL = 'Violencia Institucional'
    TRAF_ILIC_NNA_ADO_MUJ = (
        'Tráfico Ilícito de Niñas, Adolescentes y Mujeres')
    TRATA_MUJ_NNA_ADO = 'Trata de Mujeres, Niñas y Adolescentes'
    FEMICIDIO = 'Femicidio'
    FEMICIDIO_AGR = 'Femicidio Agravado'
    IND_AL_SUICIDIO = 'Inducción al Suicidio'
    OBLG_AVISO = 'Obligación de Aviso'
    OBLG_TRAM_DEN = 'Obligación de Trámites de Denuncia'
    OBLG_IMP_CORREC = 'Obligación de Implementación de Correctivos'
    REINCIDENCIA = 'Reincidencia'
    OTRO_DELITO = 'Otros'
    OPCIONES_DELITO = (
        (PSICOLOGICA, 'Violencia Psicológica'),
        (ACOSO_HOST, 'Acoso u Hostigamiento'),
        (AMENAZA, 'Amenaza'),
        (FISICA, 'Violencia Física'),
        (FISICA_AGR, 'Violencia Física Agravada'),
        (SEXUAL, 'Violencia Sexual'),
        (ACT_CARN_VICT_VUL, 'Acto Carnal con Víctima Vulnerable'),
        (ACT_LASC, 'Actos Lascivos'),
        (PROST_FORZADA, 'Prostitución Forzada'),
        (ESCLAVITUD_SEXUAL, 'Esclavitud Sexual'),
        (ACOSO_SEXUAL, 'Acoso Sexual'),
        (LABORAL, 'Violencia Laboral'),
        (PATRIM_ECO, 'Violencia Patrimonial y Económica'),
        (OBSTETRICA, 'Violencia Obstetrica'),
        (ESTERIL_FORZADA, 'Esterilización Forzada'),
        (OFENSA_PUBLICA, 'Ofensa Pública'),
        (INSTITUCIONAL, 'Violencia Institucional'),
        (TRAF_ILIC_NNA_ADO_MUJ,
            'Tráfico Ilicito de Niñas, Adolescentes y Mujeres'),
        (TRATA_MUJ_NNA_ADO, 'Trata Mujeres, Niña y Adolescentes'),
        (FEMICIDIO, 'Femicidio'),
        (FEMICIDIO_AGR, 'Femicidio Agravado'),
        (IND_AL_SUICIDIO, 'Inducción al Suicidio'),
        (OBLG_AVISO, 'Obligación de Aviso'),
        (OBLG_TRAM_DEN, 'Obligación de Trámites de Denuncia'),
        (OBLG_IMP_CORREC, 'Obligación de Implementación de Correctivos'),
        (OTRO_DELITO, 'Otros')
    )

    nro_expediente = models.CharField(
        max_length=20, default='', primary_key=True)
    procedencia = models.CharField(max_length=16, choices=OPCIONES_PROCEDENCIA)
    solicitud = models.CharField(max_length=23, choices=OPCIONES_SOLICITUDES)
    delito = models.CharField(max_length=50, choices=OPCIONES_DELITO)
    fecha_ingreso = models.DateField(default=date.today)
    personas = models.ManyToManyField(Persona)
    estado = models.CharField(max_length=9, choices=OPCIONES_ESTADO,
        default=PENDIENTE)
    edit = models.BooleanField(default=False)
    is_editing = models.CharField(max_length=9, default=0)


class Actividad(models.Model):
    SOLICITUD_CITA = 'Solicitud de Cita'
    TRIAJE_EVALUACION = 'Triaje y Evaluación'
    CONTENCION = 'Contención'
    NOTF_RECIBIDA = 'Notificación Recibida'
    NOTF_ENVIADA = 'Notificación Enviada'
    REMISION_INFORME = 'Remisión de Informe'
    VISITA_DOM = 'Visita Domiciliaria'
    ORIENTACION = 'Orientación'
    AUDIENCIA = 'Audiencia'
    PRUEBA_ANT = 'Prueba Anticipada'
    REF_SALUD = 'Referencia a Centro de Salud'
    CARTA_CULM = 'Carta de Culminación'
    LLAMADA_TELF = 'Llamada Telefónica'
    TALLER = 'Taller'
    OPCIONES_ACTIVIDAD = (
        (SOLICITUD_CITA, 'Solicitud de Cita'),
        (TRIAJE_EVALUACION, 'Triaje y Evaluación'),
        (CONTENCION, 'Contención'),
        (NOTF_RECIBIDA, 'Notificación Recibida'),
        (NOTF_ENVIADA, 'Notificación Enviada'),
        (REMISION_INFORME, 'Remision de Informe'),
        (VISITA_DOM, 'Visita Domiciliaria'),
        (ORIENTACION, 'Orientación'),
        (AUDIENCIA, 'Audiencia'),
        (PRUEBA_ANT, 'Prueba Anticipada'),
        (REF_SALUD, 'Referencia a Centro de Salud'),
        (CARTA_CULM, 'Carta de Culminación'),
        (LLAMADA_TELF, 'Llamada Telefónica'),
        (TALLER, 'Taller')
    )
    descripcion = models.CharField(max_length=28, choices=OPCIONES_ACTIVIDAD)
    participante = models.ForeignKey(Persona, on_delete=models.CASCADE)
    fecha = models.DateTimeField(default=datetime.today)


class Triaje(models.Model):
    ORIENTACION = 'Orientación'
    EVALUACION = 'Evaluación'
    REMISION_EXTERNA = 'Remisión Externa'
    OPCIONES_ACCION = (
        (ORIENTACION, 'Orientación'),
        (EVALUACION, 'Evaluación'),
        (REMISION_EXTERNA, 'Remisión Externa')
    )

    ASESORIA_JURIDICA = 'Asesoría Jurídica'
    TRABAJO_SOCIAL = 'Trabajo Social'
    MEDICINA = 'Medicina'
    PSICOLOGIA = 'Psicología'
    EDUCACION = 'Educación'
    OPCIONES_DERIVACION = (
        (ASESORIA_JURIDICA, 'Asesoría Jurídica'),
        (TRABAJO_SOCIAL, 'Trabajo Social'),
        (MEDICINA, 'Medicina'),
        (PSICOLOGIA, 'Psicología'),
        (EDUCACION, 'Educación'),
    )

    causa = models.OneToOneField(Causa, on_delete=models.CASCADE, default=None)
    genograma_imputado = models.TextField(blank=True)
    genograma_victima = models.TextField(blank=True)
    testimonio_imputado = models.TextField(blank=True)
    testimonio_victima = models.TextField(blank=True)
    impresion_diagnostica = models.TextField(blank=True)
    modalidad = models.CharField('Modalidad de Intervención',
                                 choices=OPCIONES_ACCION, max_length=16)
    observaciones = models.TextField(blank=True)
    derivacion = models.CharField('Derivacion a equipo interdisciplinario',
                                  choices=OPCIONES_DERIVACION, max_length=17)
    proxima_cita = models.DateField(
        default=(date.today() + timedelta(days=7)))
    atendido_por = models.CharField(max_length=50)

class Movimiento(models.Model):
    descripcion = models.CharField(max_length=28)
    causa = models.ForeignKey(Causa, on_delete=models.CASCADE)
    fecha = models.DateTimeField(default=datetime.today)
    realizado_por = models.CharField(max_length=50)

talleres/models.py
from django.db import models
from personas.models import Persona

# Create your models here.


class Grupo(models.Model):
    nombre = models.CharField(max_length=30, default='', primary_key=True)
    tematica = models.CharField(max_length=50, default='')
    participantes = models.ManyToManyField(Persona)
    fecha_inicio = models.DateField(default=None)
    fecha_final = models.DateField(default=None)

class Sesion(models.Model):
	PENDIENTE = 'Pendiente'
	REALIZADA = 'Realizada'
	CANCELADA = 'Cancelada'
	OPCIONES_ESTADO = (
		(PENDIENTE, 'Pendiente'),
		(REALIZADA, 'Realizada'),
		(CANCELADA, 'Cancelada'),
	)

	grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)
	fecha = models.DateField(default=None)
	estado = models.CharField(choices=OPCIONES_ESTADO, max_length=9)
	asistentes = models.ManyToManyField(Persona)

causas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test

from smc.views import logeado
from personas.models import Persona
from usuarios.models import BitacoraAcceso
from .models import Causa, Actividad, Triaje
from .forms import FormularioCausa, FormularioTriaje, FormularioActividad

# Create your views here.
 

@user_passes_test(logeado, login_url='/login/')
def nueva_causa(request):
    formulario = FormularioCausa()

    if request.method == 'POST':
        formulario = FormularioCausa(request.POST)

        if formulario.is_valid():
            formulario.save()
            return redirect('/causas/')

    return render(request, 'formulario.html',
                  {
                      'formulario': formulario,
                      'titulo': 'Registrar una nueva causa',
                  })


@user_passes_test(logeado, login_url='/login/')
def ver_causas(request):
    causas = Causa.objects.all()
    return render(request, 'causas/causas.html',
      {
        'causas': causas,
      })


@user_passes_test(logeado, login_url='/login/')
def ver_causa(request, nro_expediente):
    try:
        causa = Causa.objects.get(nro_expediente=nro_expediente)
        BitacoraAcceso.objects.create(
            usuario=request.user,
            tabla='causas_causa',
            registro=causa.nro_expediente,
            accion='Consultar'
        )
    except Exception as e:
        print(e)
        return render(request, 'causas/no_existe.html')

    victimas = causa.personas.get_queryset().filter(condicion=Persona.VICTIMA)
    imputados = causa.personas.get_queryset().filter(
        condicion=Persona.IMPUTADO)
    return render(request, 'causas/info.html',
                  {
                      'causa': causa,
                      'victimas': victimas,
                      'imputados': imputados,
                  })

@user_passes_test(logeado, login_url='/login/')
def buscar(request):
    q = request.GET.get('nro_expediente', '')

    if q:
        return redirect('/causas/ver/' + q + '/')
    else:
        return redirect('/causas/')

@user_passes_test(logeado, login_url='/login/')
def agregar_actividad(request):
    if request.method == 'POST' and all(request.POST.values()):
        formulario = FormularioActividad()
        ci = request.POST.get('ci', '')
        return render(request, 'causas/formulario_actividad.html',
          {
            'ci': ci,
            'formulario': formulario
          })
    return redirect('/causas/')


@user_passes_test(logeado, login_url='/login/')
def registrar_actividad(request):
    if request.method == 'POST' and all(request.POST.values()):
        ci = request.POST.get('ci', '')
        descripcion = request.POST.get('descripcion', '')
        persona = Persona.objects.get(ci=ci)
        actividad = Actividad.objects.create(
            descripcion=descripcion,
            participante=persona,
        )

        BitacoraAcceso.objects.create(
            usuario=request.user,
            tabla='causas_actividad',
            registro=actividad.id,
            accion='Insertar'
        )

        return redirect('/personas/' + ci + '/')
    return redirect('/causas/')


@user_passes_test(logeado, login_url='/login/')
def modificar_causa(request, nro_expediente):
    causa = Causa.objects.get(nro_expediente=nro_expediente)

    if causa.edit == False:
        causa.edit = True
        causa.is_editing = request.user.ci
        causa.save()

    else:
        if causa.edit == True and request.user.ci == causa.is_editing:

            if request.method == 'POST':
                formulario = FormularioCausa(request.POST, instance=causa)

                if formulario.is_valid():
                    causa.edit = False
                    causa.save()
                    formulario.save()

                    BitacoraAcceso.objects.create(
                        usuario=request.user,
                        tabla='causas_causa',
                        registro=causa.nro_expediente,
                        accion='Modificar'
                    )

                    return redirect('/causas/ver/' + nro_expediente + '/')

            formulario = FormularioCausa(instance=causa)
            victimas = causa.personas.get_queryset().filter(condicion=Persona.VICTIMA)
            imputados = causa.personas.get_queryset().filter(
              condicion=Persona.IMPUTADO)

            return render(request, 'causas/formulario_causa.html',
                        {
                            'formulario': formulario,
                            'titulo': 'Modificar ' + nro_expediente,
                            'nro_expediente': nro_expediente,
                            'victimas': victimas,
                            'imputados': imputados
                        })
        else:
          return redirect('/edit_bloqueado.html')


@user_passes_test(logeado, login_url='/login')
def remover_persona(request, ci, nro_expediente):
    causa = Causa.objects.get(nro_expediente=nro_expediente)
    persona = Persona.objects.get(ci=ci)

    if causa and persona:
        persona_id = persona.id
        causa.personas.remove(persona)

        BitacoraAcceso.objects.create(
            usuario=request.user,
            tabla='personas_persona',
            registro=persona_id,
            accion='Eliminar'
        )

        return redirect('/causas/modificar/' + nro_expediente + '/')

    return redirect('/causas/ver/' + nro_expediente + '/')


@user_passes_test(logeado, login_url='/login/')
def eliminar_causa(request, nro_expediente):
    causa = Causa.objects.get(nro_expediente=nro_expediente)

    if causa:
        causa_id = causa.id
        causa.delete()

        BitacoraAcceso.objects.create(
            usuario=request.user,
            tabla='causas_causa',
            registro=causa_id,
            accion='Eliminar'
        )

    return redirect('/causas/')


@user_passes_test(logeado, login_url='/login/')
def agregar_triaje(request, nro_expediente):
    causa = Causa.objects.get(nro_expediente=nro_expediente)

    if causa:
        formulario = FormularioTriaje()
        if request.method == 'POST':
            formulario = FormularioTriaje(request.POST)

            if formulario.is_valid():
                datos = formulario.cleaned_data
                triaje = Triaje.objects.create(
                    causa=causa,
                    atendido_por=request.user.get_full_name(),
                    **datos)
                BitacoraAcceso.objects.create(
                    usuario=request.user,
                    tabla='causas_triaje',
                    registro=triaje.id,
                    accion='Insertar'
                )
                return redirect('/causas/ver/' + nro_expediente + '/')

        return render(request, 'formulario.html',
                      {
                          'formulario': formulario,
                          'titulo': 'Triaje',
                      })

    return redirect('/causas/')

templates/causas/causas.html
{% extends 'base.html' %}

{% block titulo %}Causas{% endblock %}
{% block nav_causas %}active{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<a href="/causas/ingreso/" class="btn btn-success">
				<i class="fa fa-plus"></i>
				Registrar un ingreso
			</a>
		</div>
		<div class="col-md-9">
			<form class="form-inline" action="/causas/buscar/" method="get">
				<div class="input-append">
					<input class="span2 form-control" name="nro_expediente" id="appendedPrependedInput" type="text" required>
					<button type="submit" class="btn">Buscar</button>
				</div>
			</form>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-md-12">
			<table class="table table-hover">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Numero de Expendiente</th>
						<th scope="col">Acción</th>
					</tr>
				</thead>
				<tbody>
				{% for causa in causas %}
					<tr>
						<th scope="row">{{ forloop.counter }}</th>
						<td>{{ causa.nro_expediente }}</td>
						<td>
							<a href="/causas/ver/{{ causa.nro_expediente }}/" class="btn btn-info">Ver</a>
						</td>
					</tr>
				{% empty %}
					<h2 class="text-center">No hay causas registradas</h2>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

templates/causas/formulario.html
{% extends 'base.html' %}

{% block titulo %}{{ titulo }}{% endblock %}
{% block nav_causas %}active{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1 >{{ titulo }}</h1>
			<form method="POST" class="form-control">{% csrf_token %}
			{% for campo in formulario %}
				{{ campo.errors }}
				<label for="{{ campo.id_for_label }}" class="control-label">{{ campo.label }}</label>
				{{ campo }}
				<br>
			{% endfor %}
			{% block adicional %}{% endblock %}
				<input type="submit" value="Guardar" id="id_submit" class="btn btn-primary">
			</form>
		</div>	
	</div>
</div>
{% endblock %}

templates/causas/formulario_actividad.html
{% extends 'base.html' %}

{% block titulo %}Registrar Actividad{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="text-center">Registrar actividad</h1>

			<form method="POST" action="/causas/actividades/registrar">{% csrf_token %}
				<div class="form-group">
					{{ formulario.descripcion.errors }}
					<label for="{{ formulario.descripcion.id_for_label }}" class="control-label">{{ formulario.descripcion.label }}</label>
					{{ formulario.descripcion }}
				</div>
				<input type="hidden" name="ci" value="{{ ci }}">
				<input type="submit" value="Registrar" class="btn btn-primary">
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/causas/formulario_causa.html
{% extends 'formulario.html' %}

{% block adicional %}
<br>
<p><b>Víctima{% ifnotequal victimas|length 1 %}s{% endifnotequal %}:</b></p>
<ul>
{% for victima in victimas %}
	<li>{{ victima.ci }} - {{ victima.nombre }} {{ victima.apellido }} <a href="/causas/remover/{{ victima.ci }}/de/{{ nro_expediente }}" class="btn btn-danger">Remover</a></li>
{% endfor %}
</ul>
<br>
<p><b>Imputado{% ifnotequal imputados|length 1 %}s{% endifnotequal %}:</b></p>
<ul>
{% for imputado in imputados %}
	<li>{{ imputado.ci }} - {{ imputado.nombre }} {{ imputado.apellido }} <a href="/causas/remover/{{ imputado.ci }}/de/{{ nro_expediente }}" class="btn btn-danger">Remover</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/causas/imputados.html
{% extends 'base.html' %}

{% block titulo %}Imputados{% endblock %}
{% block nav_imputados %}active{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			
		<table class="table table-hover">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Cedula</th>
		      <th scope="col">Nombre</th>
		      <th scope="col">Accion</th>
		    </tr>
		  </thead>
		{% for imputado in imputados %}				
		  <tbody>
		    <tr class="table">
		      <th scope="row">1</th>
		      <td>{{ imputado.ci }}</td>
		      <td>{{ imputado.nombre }}</td>
		      <td><a href="/causas/personas/{{ imputado.ci }}/" class="btn btn-success">Ver</a></td>
		    </tr>
		   </tbody>
		{% empty %}
			<br>
			<h3 class="text-center">No hay imputados para mostrar. <a href="/causas/ingreso/">Registre una causa</a>.</h3p>
		{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

templates/causas/info_persona.html
{% extends 'base.html' %}

{% block titulo %}Información Personal{% endblock %}
{% block nav_imputados %}{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>Información Personal</h1>
			<p><b>Cédula de Identidad:</b> {{ persona.ci }}</p>
			<p><b>Nombre:</b> {{ persona.nombre }}</p>
			<p><b>Edad:</b> {{ persona.edad }}</p>
			<a href="/causas/personas/modificar/{{ persona.ci }}/" class="btn btn-warning">Modificar</a>
			<a href="/causas/personas/eliminar/{{ persona.ci }}/" class="btn btn-danger">Eliminar</a>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<h2>Actividades</h2>
			<form method="POST" action="/causas/actividades/nueva/">{% csrf_token %}
				<input type="hidden" name="ci" value="{{ persona.ci }}">
				<input type="submit" value="Registrar actividad" class="btn btn-primary">
			</form>
			<hr>
			{% for actividad in persona.actividad_set.all %}
				<p><b>Fecha:</b> {{ actividad.fecha }}</p>
				<p><b>Descripción:</b> {{ actividad.descripcion }}</p>
				<hr>
			{% empty %}
				<p>No hay actividades registradas.</p>
			{% endfor %}
		</div>
		<div class="col-md-6">
			<h2>Grupos de Taller</h2>
			<form method="POST" action="/talleres/agregar_a_taller/">
				{% csrf_token %}
				<input type="hidden" name="ci" value="{{ persona.ci }}">
				<input type="submit" value="Agregar a taller" class="btn btn-primary">
			</form>
			<hr>
			{% for grupo in persona.grupo_set.get_queryset %}
				<p><b>Nombre de grupo:</b> {{ grupo.nombre }}</p>
				<p><b>Temática:</b> {{ grupo.tematica }}</p>
				<hr>
			{% empty %}
				<p>Esta persona no está asignada a ningún grupo de taller.</p>
			{% endfor %}
		</div>			
	</div>
</div>
{% endblock %}

templates/causas/info_victima.html
{% extends 'base.html' %}

{% block titulo %}Información Personal{% endblock %}
{% block nav_victimas %}active{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="text-center">Información Personal</h1>
			<p><b>Cédula de Identidad:</b> {{ persona.ci }}</p>
			<p><b>Nombre:</b> {{ persona.nombre }}</p>
			<p><b>Edad:</b> {{ persona.edad }}</p>
			<hr>
		</div>
		<div class="col-md-12">
			<h2>Actividades</h2>
			<form method="POST" action="/causas/actividades/nueva/">
				{% csrf_token %}
				<input type="hidden" name="tipo" value="{{ persona.condicion }}">
				<input type="hidden" name="ci" value="{{ persona.ci }}">
				<input type="submit" value="Registrar actividad" class="btn btn-primary">
			</form>
			{% for actividad in victima.actividad_set.all %}
				<p><b>Fecha:</b> {{ actividad.fecha }}</p>
				<p><b>Descripción:</b> {{ actividad.descripcion }}</p>
				<hr>
			{% empty %}
				<p>No hay actividades registradas.</p>
			{% endfor %}
		</div>
			
	</div>
</div>
{% endblock %}

templates/causas/no_existe.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-md-12">
            <h2>Aviso</h2>
            <p>La causa que intenta buscar no existe.</p>
            <p>Pulse <a href="/causas/">aquí</a> para volver al inicio</p>
        </div>
    </div>
</div>
{% endblock %}