administracion/urls.py
from django.urls import path

from . import views

app_name = 'apps'

urlpatterns = [
	path('home/', views.home, name = 'home'),
	path('respaldo/', views.configurarRespaldo, name = 'respaldo'),
	path('table/',views.crearRespaldo, name = 'table'),
	path('change/',views.cambiarPeriodo, name = 'change'),
	path('bitacora/', views.ver_bitacora, name = 'bitacora'),
	path('bitacora_transacciones/', views.ver_bitacora_transacciones, name='bitacora_transacciones'),
]

smc/urls.py
# from django.contrib import admin
from django.urls import path, include
from smc import views
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.index),
    path('home/', views.home),
    path('login/', views.login_),
    path('logout', views.logout_),
    path('causas/', include('causas.urls')),
    path('personas/', include('personas.urls')),
    path('talleres/', include('talleres.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('estadisticas/', views.estadisticas),
    path('gestion/', include('administracion.urls', namespace = 'gestion')),
    path('edit_bloqueado.html', views.edit_bloqueado),
]

templates/auditor/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    {% block estaticos %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/css/fontawesome-all.min.css' %}">
    <style media="screen">
        .enlace { color: #000 }
        .enlace:hover { color: --blue }
    </style>
    {% endblock %}
    <title>{% block titulo %}SMC{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-dark navbar-expand-lg bg-primary" style="margin-bottom: 20px;">
        <a href="/home" class="navbar-brand">SMC-EIVCM</a>

        <ul class="nav nav-pills ml-auto">
            <li class="nav-item dropdown">

            <a a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" style="color: #fff; margin-right: 35px;">
                {{ user.get_full_name }}
            </a>

            <ul class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
                <li class="dropdown-item">
                    <a class="dropdown-link" href="/usuarios/ver/{{ user.ci }}/">
                        Ver Perfil
                    </a>
                </li>
                <li class="dropdown-item">
                    <a class="dropdown-link" href="/usuarios/cambiar_clave/">
                        Cambiar Contraseña
                    </a>
                </li>
                <div class="dropdown-divider"></div>
                <li class="dropdown-item">
                    <a class="dropdown-link" href="/logout">
                        Cerrar Sesión
                    </a>
                </li>
            </ul>
            </li>
        </ul>
    </nav>
    {% block content %}{% endblock %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

templates/auditor/bitacora.html
{% extends 'auditor/base.html' %}

{% block titulo %}{{ titulo }}{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-12">
			<h1>Bitácora de Acceso</h1>
		</div>
		<div class="col-12">
			<table class="table">
				<thead>
					<tr>
						<th>CI Usuario</th>
						<th>Tabla</th>
						<th>ID Registro</th>
						<th>Acción</th>
						<th>Fecha y Hora</th>
					</tr>
				</thead>
				<tbody>
					{% for entrada in entradas %}
					<tr>
						<td>
							<a href="/usuarios/ver/{{ entrada.usuario.ci }}">
								{{ entrada.usuario.ci }}
							</a>
						</td>
						<td>{{ entrada.tabla }}</td>
						<td>{{ entrada.registro }}</td>
						<td>{{ entrada.accion }}</td>
						<td>{{ entrada.fecha }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

templates/auditor/bitacora_transacciones.html
{% extends 'auditor/base.html' %}

{% block titulo %}{{ titulo }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Bitácora de Transacciones</h1>
        </div>
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Acción</th>
                        <th>Tabla</th>
                        <th>Campo</th>
                        <th>Registro</th>
                        <th>Valor Anterior</th>
                        <th>Valor Actual</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entrada in entradas %}
                    <tr>
                        <td>{{ entrada.accion }}</td>
                        <td>{{ entrada.tabla }}</td>
                        <td>{{ entrada.campo }}</td>
                        <td>{{ entrada.registro }}</td>
                        <td>{{ entrada.valor_anterior }}</td>
                        <td>{{ entrada.valor_actual }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/auditor/home.html
{% extends 'auditor/base.html' %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-12 text-center">
			<h1>Menú del Auditor</h1>
		</div>
		<div class="col-12 text-center">
			<div class="list-group">
				<div class="list-group-item">
					<h2>
						<i class="text-info fa fa-database"></i>
						<a href="{% url 'gestion:home' %}">Configuración de la aplicación</a>
					</h2>
				</div>
				<div class="list-group-item">
					<h2>
						<i class="text-warning fa fa-clipboard-list"></i>
						<a href="{% url 'gestion:bitacora' %}">Consultar Bitácora de Acceso</a>
					</h2>					
				</div>
			</div>
			<div class="list-group-item">
				<h2>
					<i class="text-success fa fa-clipboard-check"></i>
					<a href="{% url 'gestion:bitacora_transacciones' %}">
						Consultar Bitácora de Transacciones
					</a>
				</h2>
			</div>
		</div>
	</div>
</div>
{% endblock %}