administracion/urls.py
from django.urls import path

from . import views

app_name = 'apps'

urlpatterns = [
	path('home/', views.home, name = 'home'),
	path('respaldo/', views.configurarRespaldo, name = 'respaldo'),
	path('table/',views.crearRespaldo, name = 'table'),
	path('change/',views.cambiarPeriodo, name = 'change'),
	path('bitacora/', views.ver_bitacora, name = 'bitacora'),
	path('bitacora_transacciones/', views.ver_bitacora_transacciones, name='bitacora_transacciones'),
]

smc/urls.py
# from django.contrib import admin
from django.urls import path, include
from smc import views
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.index),
    path('home/', views.home),
    path('login/', views.login_),
    path('logout', views.logout_),
    path('causas/', include('causas.urls')),
    path('personas/', include('personas.urls')),
    path('talleres/', include('talleres.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('estadisticas/', views.estadisticas),
    path('gestion/', include('administracion.urls', namespace = 'gestion')),
    path('edit_bloqueado.html', views.edit_bloqueado),
]

administracion/models.py
from django.db import models
from datetime import date
# Create your models here.


class configuracionBDA(models.Model):
	respaldo = models.IntegerField()
	periodo = models.CharField(max_length=1)
	ultimo_respaldo = models.DateField(default=None, blank=True, null=True)
	ultima_importacion = models.DateField(default=None, blank=True, null=True)
	uitima_exportacion = models.DateField(default=None, blank=True, null=True)

class Bitacora(models.Model):
	fecha = models.DateField(default = date.today)
	descripcion = models.CharField(max_length = 15)

class BitacoraTransaccion(models.Model):
	fecha = models.DateField(default = date.today)
	accion = models.CharField(max_length=80)
	tabla = models.CharField(max_length=80, blank=True)
	campo = models.CharField(max_length=80, blank=True)
	registro = models.CharField(max_length=80, blank=True)
	valor_anterior = models.CharField(max_length=80, blank=True)
	valor_actual = models.CharField(max_length = 80, blank=True)

administracion/views.py
from django.shortcuts import render,redirect,HttpResponse
from datetime import date
from django.contrib.auth.decorators import user_passes_test
from smc.views import logeado,is_audit
from administracion.models import *
from usuarios.models import BitacoraAcceso
from .models import BitacoraTransaccion
import MySQLdb

from django.core.files.base import ContentFile
from django.core.files.storage import default_storage

from wsgiref.util import FileWrapper

# Create your views here.

@user_passes_test(is_audit, login_url = '/usuarios/sin_permiso/')
def home(request):
    respaldo = configuracionBDA.objects.get(id = 1)
    return render(request, "administracion/home.html",{'respaldo' : respaldo})

@user_passes_test(is_audit, login_url = '/usuarios/sin_permiso/')
def configurarRespaldo(request):
    respaldo = configuracionBDA.objects.get(id = 1)
    if respaldo.respaldo == 1:
        respaldo.respaldo = 0
        p = Bitacora(descripcion = 'Apagado')
    else:
        respaldo.respaldo = 1
        p = Bitacora(descripcion = 'Encendido')
    respaldo.save()
    p.save()
    return redirect('/gestion/home')

def crearRespaldo(request):
    file_content = ''
    
    # Obtenemos la conexion con la base de datos.
    db = MySQLdb.connect(user='root', db='smc', passwd='', host='localhost')
    cursor = db.cursor()
    
    # Obtenemos los nombres de las tablas.
    cursor.execute('SHOW FULL TABLES FROM smc')
    tablas = [row[0] for row in cursor.fetchall()]
    
    for fila in tablas:
        # Obtenemos los registros de cada tabla
        cursor.execute('SELECT * FROM ' + fila)
        registros = cursor.fetchall()

        if len(registros):
            for registro in registros:
                file_content += "INSERT IGNORE INTO `" + fila + "` VALUES ("
                n = len(registro)
                i = 0
                for elemento in registro:
                    file_content += "'"+str(elemento)+"'"
                    if i < n - 1:
                        file_content += ","
                    i += 1;
                file_content += ");"
        
    db.close()
    name = 'Backup.'+ str(date.today()) + ".sql" 
    path = default_storage.save(name, ContentFile(file_content))
    # print(file_content)
    # file_path = os.path.join(settings.MEDIA_ROOT, path)
    # file_name = "Backup " + str(date.today()) + ".txt"
    # file = open(file_name,'w')
    # file.write(file_content)
    # file.close()
    bitacora = Bitacora(descripcion = 'Importacion')
    bitacora.save()
    # return redirect('/gestion/home/')
    response = HttpResponse(file_content, content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename={}'.format(name)
    response['X-Sendfile'] = path
    return response

@user_passes_test(is_audit, login_url = '/usuarios/sin_permiso/')
def cambiarPeriodo(request):
    if request.method == 'POST':
        valor_nuevo = request.POST['periodo'] 
        valor = configuracionBDA.objects.get(id = 1)
        valor.periodo = valor_nuevo
        valor.save()
        bitacora = Bitacora(descripcion = 'CambioPeriodo')
        print("¡Correcto!")
        return redirect('/gestion/home')

@user_passes_test(is_audit, login_url = '/usuarios/sin_permiso')
def ver_bitacora(request):
    entradas = BitacoraAcceso.objects.all().order_by('-fecha')

    return render(request, 'auditor/bitacora.html',
                  {
                      'titulo': 'Bitácora de Acceso',
                      'entradas': entradas
                  })

# @user_passes_test(is_audit, login_url = '/usuarios/sin_permiso')
# def procesar_archivo(request):
#     if request.method == 'POST':
#         print(request)

@user_passes_test(is_audit, login_url = '/usuarios/sin_permiso')
def ver_bitacora_transacciones(request):
    entradas = BitacoraTransaccion.objects.all().order_by('id')

    return render(request, 'auditor/bitacora_transacciones.html',
                  {
                      'titulo': 'Bitácora de Acceso',
                      'entradas': entradas
                  })

templates/administracion/home.html
{% extends "base.html" %}

{% block content %}
<style>
	.info {
		display: none;
	}
	h3.badge {
		width: 78px;
	}
</style>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="text-center">Configuración de la aplicación</h1>
				<br>
				<div class="list-group">
					<a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
						<div class="d-flex w-100 justify-content-between">
							<h5 class="mb-1">Habilitar Respaldos de seguridad Automáticos</h5>
							{% if respaldo.respaldo == 1 %}
								<h3 class="badge badge-success">Habilitado</h3>
							{% else %}
								<h3 class="badge badge-danger">Desabilitado</h3>
							{% endif %}
						</div>
						<div class="info">
							<span>El ultimo respaldo fue: {{ respaldo.ultima_respaldo }}</span>
							<p class="mb-1">
								Habilite esta opcion para activar los respaldos de seguridad de los datos, y podra seleccionar el tipo de respaldo y el periodo de este.
							</p>
							<br>
							<div class="opciones">
								{% if respaldo.respaldo == 1 %}
									<button class="btn btn-success" id="btnActResp" disabled="">Activar</button>
									<button class="btn btn-danger" id="btnDesResp">Desactivar</button>
								{% else %}
									<button class="btn btn-success" id="btnActResp">Activar</button>
									<button class="btn btn-danger" id="btnDesResp" disabled="">Desactivar</button>
								{% endif %}
							</div>
						</div>
					</a>
					<a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
						<div class="d-flex w-100 justify-content-between">
							<h5 class="mb-1">Periodo de respaldo</h5>
							<h3 class="badge badge-success" id="valor-actual-periodo"></h3>
						</div>
						<div class="info">
						<form action="{% url 'gestion:change' %}" method="POST">
							{% csrf_token %}
							<input type="hidden" value="{{ respaldo.periodo }}" id="valor-periodo">
							<p class="mb-1">
								Esta opcion es se activa automaticamente cuando se esta habilitado los respaldos de seguridad, por favor elija el perio de respaldos
							</p>
							<br>
							<p>
								Fecha de último respaldo:
							</p>
							<div class="opciones form-group">
								<div class="form-check form-check-inline">
									<input name="periodo" class="form-check-input" type="radio" id="diario" value="A">
									<label class="form-check-label" for="diario">Diario</label>
								</div>
								<div class="form-check form-check-inline">
									<input name="periodo" class="form-check-input" type="radio" id="semanal" value="B">
									<label class="form-check-label" for="semanal">Semanal</label>
								</div>
								<div class="form-check form-check-inline">
									<input name="periodo" class="form-check-input" type="radio" id="mensual" value="C">
									<label class="form-check-label" for="mensual">Mensual</label>
								</div>
								<div class="form-check form-check-inline">
									<input name="periodo" class="form-check-input" type="radio" id="trimestral" value="D">
									<label class="form-check-label" for="trimestral">Trimestral</label>
								</div>
								<div class="form-check form-check-inline">
									<input name="periodo" class="form-check-input" type="radio" id="semestral" value="E">
									<label class="form-check-label" for="semestral">Semestral</label>
								</div>
								<div class="form-check form-check-inline">
									<input name="periodo" class="form-check-input" type="radio" id="anual" value="F">
									<label class="form-check-label" for="anual">Anual</label>
								</div>
								<input type="submit" class="btn btn-success" value="Guardar">
							</div>
						</form>
						</div>
					</a>
					<a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
						<div class="d-flex w-100 justify-content-between">
							<h5 class="mb-1">Exportar Base de datos</h5>
						</div>
						<div class="info">
							<p class="mb-1">
								Haga un respaldo de su base de datos haciendo clic en el siguiente boton: 
							</p>
							<br>
							<div class="opciones">
								<button class="btn btn-success" id="btnRespaldo">Descargar Respaldo</button>
							</div>
						</div>
					</a>
					<a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
						<div class="d-flex w-100 justify-content-between">
							<h5 class="mb-1">Importar base de datos</h5>
						</div>
						<div class="info">
							<p class="mb-1">
								Para reastaurar la base de datos a una copia vieja haga clic en el siguiente boton y busque el archivo sql donde está toda la información.	
							</p>
							<br>
							<div class="opciones">
								<!-- <div class="custom-file">
									<input type="file" class="custom-file-input" id="file" accept=".sql">
									<label class="custom-file-label" for="file">Seleccione un archivo</label>
								</div> -->
								<form method="POST"">
									<input type="file" accept=".sql" class="form-control">
									<br>	
									<input type="submit" class="btn btn-success" value="Restaurar">
								</form>
							</div>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>
	<br><br><br><br><br><br><br>

	<script>
		$(document).ready(function () {
			var elementos = $('.list-group-item');
			for (var elemento of elementos) {
				$(elemento).click(function () {
					if ($(this).hasClass("active")) {
						return true;
					}

					for (var e of elementos) {
						$(e).removeClass('active');
						var i = $(e).children()[1];
						$(i).slideUp(400);
					}

					$(this).addClass('active');
					var i = $(this).children()[1];
					$(i).slideDown(400);
				});
			}

			$('#btnActResp').click(function () {
				$(location).attr('href', '{% url 'gestion:respaldo' %}');
			});
			$('#btnDesResp').click(function () {
				$(location).attr('href', '{% url 'gestion:respaldo' %}');
			});
			$('#btnRespaldo').click(function () {
				$(location).attr('href', '{% url 'gestion:table' %}')
			});

			var periodo = $('#valor-periodo').val();

			if (periodo == 'A'){
				$('#diario').attr('checked','true');
				$('#valor-actual-periodo').text('Diario');
			}
			else if (periodo == 'B') {
				$('#semanal').attr('checked','true');
				$('#valor-actual-periodo').text('Semanal');
			}
			else if (periodo == 'C') {
				$('#mensual').attr('checked','true');
				$('#valor-actual-periodo').text('Mensual');
			}
			else if (periodo == 'D') {
				$('#trimestral').attr('checked','true');
				$('#valor-actual-periodo').text('Trimestral');
			}
			else if (periodo == 'E') {
				$('#semestral').attr('checked','true');
				$('#valor-actual-periodo').text('Semestral');
			}
			else if (periodo == 'F') {
				$('#anual').attr('checked','true');
				$('#valor-actual-periodo').text('Anual');
			}
		});
	</script>
{% endblock content %}

templates/administracion/restaurar.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container">
    	<div class="row">
    		<div class="col-md-12">
    			<h2 class="text-primary text-center">La restauracion se ha realizado de manera exitosa</h2>
    			<img src="{% static 'img/pulgar.jpg' %}" alt="" width="500px" style="margin-left: 200px">
    		</div>
    	</div>
    </div>
{% endblock content %}